#!/bin/bash
echo "------------------Start-------------------------------------------"
apt-get -y update
apt install openjdk-8-jdk -y
groupadd tomcat
useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
cd /tmp
curl -O https://apache-mirror.rbc.ru/pub/apache/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
mkdir /opt/tomcat
tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
cd /opt/tomcat
chgrp -R tomcat /opt/tomcat
chmod -R g+r conf
chmod g+x conf
chown -R tomcat webapps/ work/ temp/ logs/
update-java-alternatives -l
touch /etc/systemd/system/tomcat.service
echo "[Unit]
Description=Apache Tomcat Web Application Container
After=network.target

[Service]
Type=forking
                      
Environment=JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
Environment=CATALINA_HOME=/opt/tomcat
Environment=CATALINA_BASE=/opt/tomcat
Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

ExecStart=/opt/tomcat/bin/startup.sh
ExecStop=/opt/tomcat/bin/shutdown.sh

User=tomcat
Group=tomcat
UMask=0007
RestartSec=10
Restart=always

[Install]
WantedBy=multi-user.target" >> /etc/systemd/system/tomcat.service
systemctl daemon-reload
systemctl start tomcat
systemctl status tomcat
ufw allow 8080
systemctl enable tomcat
sed -i 's%<Valve className=%<!--Valve className=%' /opt/tomcat/webapps/manager/META-INF/context.xml
sed -i 's!:1|0:0:0:0:0:0:0:1" />!:1|0:0:0:0:0:0:0:1" /> -->!' /opt/tomcat/webapps/manager/META-INF/context.xml
systemctl restart tomcat

#echo "
   <role rolename="admin-gui"/>
   <role rolename="manager-gui"/>
   <user username="admin" password="admin_password" roles="admin-gui,manager-gui"/>" >> /opt/tomcat/conf/tomcat-users.xml 
#systemctl restart tomcat

echo "-------------------Stop---------------------------------------------"


